### PR TITLE
Add FileType information to the README

### LINKED ISSUE #9: Doesn't work for *.conf filetypes (and maybe others?)
I installed your plugin and was working with a `*.conf` file and noticed the colors weren't working. I thought I was messing the configuration, but it works when I'm on a `*.sass` file. [Here's a gist](https://gist.github.com/filipekiss/7dcab93717250e09ed91fa846036a8a2) with both files and a `minimal.vim`rc for reproduction.

Great plugin, btw!

| Sass File | Conf File |
| -- | -- |
|image| image|

### PR DESCRIPTION
**Pull request by filipekiss**
Closes #9

### CODE REVIEW

**Comment by norcalli** [comment]
Lovely! Thank you. Ha, yeah I didn't publicize the `:ReloadBufferColorizer` command since it has some edge cases with respecting the options from `setup()` command because I wanted to avoid global state, but for this purpose, it definitely works well.

**Comment by norcalli** [comment]
Oh, also `:ReloadBufferColorizer` doesn't attach_to_buffer and continue highlighting, which is another reason why I didn't publicize it. It was for reloading if you changed the settings, but, as I mentioned, that had some edge cases. Maybe I'll add a `ColorizerAttachToBuffer` command and rename `ReloadBufferColorizer` to `ColorizerReloadBufferOptions`.

**Comment by filipekiss** [comment]
I've added the `ColorizerAttachToBuffer` command as you mentioned on #9. Is the hardcoded `0` ok for this? I'm not sure how the Lua API works regarding buffer numbers :P

**Comment by norcalli** [comment]
Even better! 0 indicates the current buffer in the Lua neovim apis (also for window commands it indicates the current window).

**Comment by norcalli** [comment]
The only thing is that it won't respect the default options if you have used `setup()` but that's more of a bug and something I'll fix.

**Comment by filipekiss** [comment]
Glad I could help :D Thank you again for the plugin!

**Pull request merged**
